version: "3.8"

services:
  dashboard:
    build: .
    container_name: vm_dashboard
    env_file:
      - secrets/secrets.env
    volumes:
      - ./userdata:/app/userdata
      - /srv/vm_dashboard/data:/data
      - /srv/shared/nginx-acl:/nginx-acl:rw

    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - dashboard
    ports:
      - "443:443"
      - "25565:25565"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/streams:/etc/nginx/streams
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - /srv/shared/nginx-acl:/etc/nginx/acl:ro

    restart: unless-stopped

  certbot:
    build:
      context: ./docker/certbot        # see Dockerfile below
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./secrets:/secrets:ro          # <-- porkbun.ini lives here
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
    restart: "no"

